import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import TeacherDashboardLayout from '@/components/layout/TeacherDashboardLayout';
import { useTeacherMode } from '@/contexts/TeacherModeContext';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import {
  Plus, Search, Filter, CheckCircle, Clock, AlertTriangle,
  Phone, FileText, TrendingUp, ClipboardList, Calendar, MoreHorizontal, AlertCircle, Trash2, Edit
} from 'lucide-react';
import { teacherTasks, classStudents } from '@/data/teacherMockData';
import { toast } from 'sonner';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';

const TeacherTasksContent = () => {
  const navigate = useNavigate();
  const { currentMode } = useTeacherMode();
  const [tasks, setTasks] = useState(teacherTasks);
  const [searchQuery, setSearchQuery] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [priorityFilter, setPriorityFilter] = useState('all');
  const [isCreateOpen, setIsCreateOpen] = useState(false);
  const [isCompleteOpen, setIsCompleteOpen] = useState(false);
  const [selectedTask, setSelectedTask] = useState<typeof tasks[0] | null>(null);
  const [formData, setFormData] = useState({
    studentId: '',
    type: 'Call Parent',
    priority: 'medium',
    dueDate: '',
    description: '',
  });
  const [completeNotes, setCompleteNotes] = useState('');

  // Mode restriction
  if (currentMode !== 'class_teacher') {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
        <AlertCircle className="w-16 h-16 text-muted-foreground mb-4" />
        <h2 className="text-xl font-semibold mb-2">Class Teacher Mode Required</h2>
        <p className="text-muted-foreground mb-4">Tasks are only accessible in Class Teacher mode.</p>
        <Button onClick={() => navigate('/teacher')}>Back to Dashboard</Button>
      </div>
    );
  }

  const filteredTasks = tasks.filter(task => {
    const matchesSearch = task.studentName.toLowerCase().includes(searchQuery.toLowerCase()) ||
      task.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus = statusFilter === 'all' || task.status === statusFilter;
    const matchesType = typeFilter === 'all' || task.type === typeFilter;
    const matchesPriority = priorityFilter === 'all' || task.priority === priorityFilter;
    return matchesSearch && matchesStatus && matchesType && matchesPriority;
  });

  const pendingTasks = tasks.filter(t => t.status === 'pending');
  const inProgressTasks = tasks.filter(t => t.status === 'in-progress');
  const completedTasks = tasks.filter(t => t.status === 'completed');
  const overdueTasks = tasks.filter(t => {
    if (t.status === 'completed') return false;
    const dueDate = new Date(t.dueDate);
    const today = new Date();
    return dueDate < today;
  });

  const handleCreateTask = () => {
    if (!formData.studentId || !formData.dueDate || !formData.description) {
      toast.error('Please fill in all required fields');
      return;
    }

    const student = classStudents.find(s => s.id === formData.studentId);
    if (!student) {
      toast.error('Student not found');
      return;
    }

    const newTask = {
      id: `t${Date.now()}`,
      studentId: formData.studentId,
      studentName: student.name,
      type: formData.type,
      priority: formData.priority,
      status: 'pending' as const,
      dueDate: formData.dueDate,
      createdDate: new Date().toISOString().split('T')[0],
      description: formData.description,
      notes: '',
      autoGenerated: false,
    };

    setTasks(prev => [newTask, ...prev]);
    setIsCreateOpen(false);
    setFormData({ studentId: '', type: 'Call Parent', priority: 'medium', dueDate: '', description: '' });
    toast.success('Task created successfully');
  };

  const handleCompleteTask = () => {
    if (!selectedTask) return;

    setTasks(prev => prev.map(t =>
      t.id === selectedTask.id
        ? { ...t, status: 'completed' as const, notes: completeNotes, completedDate: new Date().toISOString().split('T')[0] }
        : t
    ));
    setIsCompleteOpen(false);
    setSelectedTask(null);
    setCompleteNotes('');
    toast.success('Task marked as completed');
  };

  const handleDeleteTask = (taskId: string) => {
    setTasks(prev => prev.filter(t => t.id !== taskId));
    toast.success('Task deleted');
  };

  const handleStatusChange = (taskId: string, newStatus: 'pending' | 'in-progress' | 'completed') => {
    setTasks(prev => prev.map(t => t.id === taskId ? { ...t, status: newStatus } : t));
    toast.success(`Task status updated to ${newStatus}`);
  };

  const getTaskIcon = (type: string) => {
    switch (type) {
      case 'Call Parent': return Phone;
      case 'Remedial Plan': return FileText;
      case 'Monitor Progress': return TrendingUp;
      case 'Submit Report': return ClipboardList;
      default: return ClipboardList;
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case 'high': return 'bg-red-50 text-red-700 border-red-200';
      case 'medium': return 'bg-amber-50 text-amber-700 border-amber-200';
      case 'low': return 'bg-blue-50 text-blue-700 border-blue-200';
      default: return 'bg-gray-50 text-gray-700 border-gray-200';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'bg-emerald-50 text-emerald-700 border-emerald-200';
      case 'in-progress': return 'bg-blue-50 text-blue-700 border-blue-200';
      case 'pending': return 'bg-gray-50 text-gray-700 border-gray-200';
      default: return 'bg-gray-50 text-gray-700 border-gray-200';
    }
  };

  const isOverdue = (task: typeof tasks[0]) => {
    if (task.status === 'completed') return false;
    const dueDate = new Date(task.dueDate);
    const today = new Date();
    return dueDate < today;
  };

  return (
    <div className="space-y-6 max-w-[1600px]">
      {/* Header */}
      <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">Tasks & Follow-ups</h1>
          <p className="text-sm text-gray-500 mt-1">Track actions and interventions for your students</p>
        </div>
        <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
          <DialogTrigger asChild>
            <Button className="gap-2">
              <Plus className="w-4 h-4" />
              Create Task
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Create New Task</DialogTitle>
            </DialogHeader>
            <div className="space-y-4 pt-4">
              <div className="space-y-2">
                <Label>Student *</Label>
                <Select value={formData.studentId} onValueChange={(v) => setFormData(prev => ({ ...prev, studentId: v }))}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select student" />
                  </SelectTrigger>
                  <SelectContent>
                    {classStudents.map(student => (
                      <SelectItem key={student.id} value={student.id}>{student.name}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Task Type *</Label>
                  <Select value={formData.type} onValueChange={(v) => setFormData(prev => ({ ...prev, type: v }))}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Call Parent">Call Parent</SelectItem>
                      <SelectItem value="Remedial Plan">Remedial Plan</SelectItem>
                      <SelectItem value="Monitor Progress">Monitor Progress</SelectItem>
                      <SelectItem value="Submit Report">Submit Report</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Priority *</Label>
                  <Select value={formData.priority} onValueChange={(v) => setFormData(prev => ({ ...prev, priority: v }))}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="high">High</SelectItem>
                      <SelectItem value="medium">Medium</SelectItem>
                      <SelectItem value="low">Low</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>
              <div className="space-y-2">
                <Label>Due Date *</Label>
                <Input type="date" value={formData.dueDate} onChange={(e) => setFormData(prev => ({ ...prev, dueDate: e.target.value }))} />
              </div>
              <div className="space-y-2">
                <Label>Description *</Label>
                <Textarea rows={3} value={formData.description} onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))} placeholder="Describe the task..." />
              </div>
              <Button onClick={handleCreateTask} className="w-full">Create Task</Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="rounded-xl shadow-sm border-0">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-gray-100 flex items-center justify-center">
                <Clock className="w-5 h-5 text-gray-600" />
              </div>
              <div>
                <p className="text-xs text-gray-500">Pending</p>
                <p className="text-2xl font-bold text-gray-900">{pendingTasks.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="rounded-xl shadow-sm border-0">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center">
                <TrendingUp className="w-5 h-5 text-blue-600" />
              </div>
              <div>
                <p className="text-xs text-gray-500">In Progress</p>
                <p className="text-2xl font-bold text-blue-600">{inProgressTasks.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="rounded-xl shadow-sm border-0">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-emerald-100 flex items-center justify-center">
                <CheckCircle className="w-5 h-5 text-emerald-600" />
              </div>
              <div>
                <p className="text-xs text-gray-500">Completed</p>
                <p className="text-2xl font-bold text-emerald-600">{completedTasks.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="rounded-xl shadow-sm border-0 bg-red-50">
          <CardContent className="p-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-red-200 flex items-center justify-center">
                <AlertTriangle className="w-5 h-5 text-red-600" />
              </div>
              <div>
                <p className="text-xs text-red-600">Overdue</p>
                <p className="text-2xl font-bold text-red-700">{overdueTasks.length}</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Filters */}
      <Card className="rounded-xl shadow-sm border-0">
        <CardContent className="p-4">
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
              <Input
                placeholder="Search tasks or students..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-full sm:w-40">
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Status</SelectItem>
                <SelectItem value="pending">Pending</SelectItem>
                <SelectItem value="in-progress">In Progress</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
              </SelectContent>
            </Select>
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-full sm:w-48">
                <SelectValue placeholder="Type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                <SelectItem value="Call Parent">Call Parent</SelectItem>
                <SelectItem value="Remedial Plan">Remedial Plan</SelectItem>
                <SelectItem value="Monitor Progress">Monitor Progress</SelectItem>
                <SelectItem value="Submit Report">Submit Report</SelectItem>
              </SelectContent>
            </Select>
            <Select value={priorityFilter} onValueChange={setPriorityFilter}>
              <SelectTrigger className="w-full sm:w-40">
                <SelectValue placeholder="Priority" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Priority</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="low">Low</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Tasks List */}
      <div className="space-y-3">
        <h2 className="text-sm font-semibold text-gray-400 uppercase tracking-wide">
          {filteredTasks.length} Tasks
        </h2>
        {filteredTasks.length > 0 ? (
          <div className="space-y-3">
            {filteredTasks.map((task) => {
              const TaskIcon = getTaskIcon(task.type);
              const overdueStatus = isOverdue(task);

              return (
                <Card key={task.id} className={`rounded-xl shadow-sm border-0 ${overdueStatus ? 'border-2 border-red-200' : ''}`}>
                  <CardContent className="p-4">
                    <div className="flex flex-col md:flex-row md:items-center gap-4">
                      {/* Left: Icon & Info */}
                      <div className="flex items-start gap-4 flex-1 min-w-0">
                        <div className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${getPriorityColor(task.priority)}`}>
                          <TaskIcon className="w-6 h-6" />
                        </div>

                        <div className="flex-1 min-w-0">
                          <div className="flex items-start gap-2 mb-2">
                            <div className="flex-1">
                              <h3 className="font-semibold text-gray-900 mb-1">{task.type}</h3>
                              <p className="text-sm text-gray-600 cursor-pointer hover:text-primary" onClick={() => navigate(`/teacher/student-profile/${task.studentId}`)}>
                                {task.studentName}
                              </p>
                            </div>
                            {task.autoGenerated && (
                              <Badge variant="outline" className="bg-purple-50 text-purple-700 border-purple-200 text-xs">
                                Auto
                              </Badge>
                            )}
                          </div>
                          <p className="text-sm text-gray-700 mb-2">{task.description}</p>
                          <div className="flex flex-wrap items-center gap-2">
                            <div className="flex items-center gap-1 text-xs text-gray-500">
                              <Calendar className="w-3 h-3" />
                              Due: {task.dueDate}
                            </div>
                            {overdueStatus && (
                              <Badge className="bg-red-500 text-white text-xs">Overdue</Badge>
                            )}
                            <Badge variant="outline" className={`${getPriorityColor(task.priority)} text-xs`}>
                              {task.priority}
                            </Badge>
                          </div>
                        </div>
                      </div>

                      {/* Right: Status & Actions */}
                      <div className="flex items-center gap-2 md:flex-col md:items-end">
                        <Badge variant="outline" className={`${getStatusColor(task.status)} whitespace-nowrap`}>
                          {task.status === 'in-progress' ? 'In Progress' : task.status}
                        </Badge>

                        <div className="flex items-center gap-1">
                          {task.status !== 'completed' && (
                            <>
                              {task.status === 'pending' && (
                                <Button
                                  size="sm"
                                  variant="outline"
                                  className="h-8 text-xs"
                                  onClick={() => handleStatusChange(task.id, 'in-progress')}
                                >
                                  Start
                                </Button>
                              )}
                              <Button
                                size="sm"
                                className="h-8 gap-1 text-xs"
                                onClick={() => {
                                  setSelectedTask(task);
                                  setIsCompleteOpen(true);
                                }}
                              >
                                <CheckCircle className="w-3 h-3" />
                                Complete
                              </Button>
                            </>
                          )}
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button variant="ghost" size="icon" className="h-8 w-8">
                                <MoreHorizontal className="w-4 h-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem onClick={() => navigate(`/teacher/student-profile/${task.studentId}`)}>
                                View Student Profile
                              </DropdownMenuItem>
                              <DropdownMenuItem onClick={() => handleDeleteTask(task.id)} className="text-red-600">
                                <Trash2 className="w-4 h-4 mr-2" />
                                Delete Task
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </div>
                      </div>
                    </div>

                    {task.notes && task.status === 'completed' && (
                      <div className="mt-4 pt-4 border-t">
                        <p className="text-xs text-gray-500 mb-1">Completion Notes:</p>
                        <p className="text-sm text-gray-700 bg-gray-50 rounded-lg p-3">{task.notes}</p>
                        {task.completedDate && (
                          <p className="text-xs text-gray-500 mt-2">Completed on: {task.completedDate}</p>
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
              );
            })}
          </div>
        ) : (
          <Card className="rounded-xl shadow-sm border-0">
            <CardContent className="py-16 text-center">
              <ClipboardList className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-gray-900 mb-2">No tasks found</h3>
              <p className="text-gray-500 mb-4">
                {searchQuery || statusFilter !== 'all' || typeFilter !== 'all' || priorityFilter !== 'all'
                  ? 'Try adjusting your filters'
                  : 'Create your first task to get started'}
              </p>
            </CardContent>
          </Card>
        )}
      </div>

      {/* Complete Task Dialog */}
      <Dialog open={isCompleteOpen} onOpenChange={setIsCompleteOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Complete Task</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 pt-4">
            {selectedTask && (
              <>
                <div className="bg-gray-50 rounded-lg p-4">
                  <p className="text-sm font-medium text-gray-900 mb-1">{selectedTask.type}</p>
                  <p className="text-sm text-gray-600">{selectedTask.studentName}</p>
                  <p className="text-sm text-gray-700 mt-2">{selectedTask.description}</p>
                </div>
                <div className="space-y-2">
                  <Label>Completion Notes (Optional)</Label>
                  <Textarea
                    rows={4}
                    value={completeNotes}
                    onChange={(e) => setCompleteNotes(e.target.value)}
                    placeholder="Add any notes about the task completion..."
                  />
                </div>
                <div className="flex gap-2">
                  <Button onClick={handleCompleteTask} className="flex-1">
                    Mark as Completed
                  </Button>
                  <Button variant="outline" onClick={() => setIsCompleteOpen(false)} className="flex-1">
                    Cancel
                  </Button>
                </div>
              </>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

const TeacherTasks = () => {
  return (
    <TeacherDashboardLayout>
      <TeacherTasksContent />
    </TeacherDashboardLayout>
  );
};

export default TeacherTasks;
